module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-primary": "var(--app-primary)",
        brandprimary: "var(--brandprimary)",
        "color-5": "var(--color-5)",
        "color-black-2": "var(--color-black-2)",
        "color-error": "var(--color-error)",
        "color-grey-3": "var(--color-grey-3)",
        "color-grey-5": "var(--color-grey-5)",
        "color-white": "var(--color-white)",
        colorblack: "var(--colorblack)",
        colorwhite: "var(--colorwhite)",
        "dark-medium": "var(--dark-medium)",
        "error-100": "var(--error-100)",
        "error-200": "var(--error-200)",
        "error-700": "var(--error-700)",
        "global-colorsneutral100": "var(--global-colorsneutral100)",
        "gray-01": "var(--gray-01)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-400": "var(--gray-400)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-900": "var(--gray-900)",
        "gray-input": "var(--gray-input)",
        "grey-30": "var(--grey-30)",
        "grey-medium": "var(--grey-medium)",
        "light-stroke": "var(--light-stroke)",
        "m-3syslightbackground": "var(--m-3syslightbackground)",
        "m-3syslightprimary": "var(--m-3syslightprimary)",
        "m-3syslightsurface": "var(--m-3syslightsurface)",
        "m-3white": "var(--m-3white)",
        "m3syslightinverse-on-surface": "var(--m3syslightinverse-on-surface)",
        "m3syslighton-surface": "var(--m3syslighton-surface)",
        "m3syslighton-surface-variant": "var(--m3syslighton-surface-variant)",
        "neutral-600": "var(--neutral-600)",
        "neutral-700": "var(--neutral-700)",
        "primary-100": "var(--primary-100)",
        "primary-200": "var(--primary-200)",
        "primary-700": "var(--primary-700)",
        "primary-color-change": "var(--primary-color-change)",
        red: "var(--red)",
        "secondary-color-change": "var(--secondary-color-change)",
        "shadesgreyswhite-600": "var(--shadesgreyswhite-600)",
        shadeswhite: "var(--shadeswhite)",
        "slate-200": "var(--slate-200)",
        sucess: "var(--sucess)",
        systemsuccess: "var(--systemsuccess)",
        "tertiary-color": "var(--tertiary-color)",
        text: "var(--text)",
        "warning-100": "var(--warning-100)",
        "warning-200": "var(--warning-200)",
        "warning-700": "var(--warning-700)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-base": "var(--body-base-font-family)",
        "body-base-medium": "var(--body-base-medium-font-family)",
        "body-large": "var(--body-large-font-family)",
        "body-m": "var(--body-m-font-family)",
        "body-s": "var(--body-s-font-family)",
        "body-small-medium": "var(--body-small-medium-font-family)",
        "body-small-regular": "var(--body-small-regular-font-family)",
        "body-strong": "var(--body-strong-font-family)",
        h5: "var(--h5-font-family)",
        "heading-bold-h4": "var(--heading-bold-h4-font-family)",
        "heading-desktop-h5": "var(--heading-desktop-h5-font-family)",
        "headline-large": "var(--headline-large-font-family)",
        "label-large": "var(--label-large-font-family)",
        "m3-body-large": "var(--m3-body-large-font-family)",
        "m3-body-medium": "var(--m3-body-medium-font-family)",
        "m3-headline-small": "var(--m3-headline-small-font-family)",
        "m3-label-large": "var(--m3-label-large-font-family)",
        "m3-label-medium": "var(--m3-label-medium-font-family)",
        "m3-label-small": "var(--m3-label-small-font-family)",
        navigation: "var(--navigation-font-family)",
        "normal-medium": "var(--normal-medium-font-family)",
        "small-text": "var(--small-text-font-family)",
        "title-large": "var(--title-large-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "drop-shadow-200": "var(--drop-shadow-200)",
        shadow: "var(--shadow)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
